// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0CApe1dH9t6Bp-QWM5EIaBHCz6I7FEQ',
    appId: '1:365499300665:web:4a798546a730a86c9146e8',
    messagingSenderId: '365499300665',
    projectId: 'starson-pos-2025',
    authDomain: 'starson-pos-2025.firebaseapp.com',
    storageBucket: 'starson-pos-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAigKPJge5k8tfzN9eDpKcU6E_n-icxRjQ',
    appId: '1:365499300665:android:4db6115a21681edf9146e8',
    messagingSenderId: '365499300665',
    projectId: 'starson-pos-2025',
    storageBucket: 'starson-pos-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFtxEDefbt573Xmfh6Urk4jI-A8o74iQ',
    appId: '1:365499300665:ios:200d915d6454eff79146e8',
    messagingSenderId: '365499300665',
    projectId: 'starson-pos-2025',
    storageBucket: 'starson-pos-2025.firebasestorage.app',
    iosBundleId: 'com.example.starsonFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFFtxEDefbt573Xmfh6Urk4jI-A8o74iQ',
    appId: '1:365499300665:ios:200d915d6454eff79146e8',
    messagingSenderId: '365499300665',
    projectId: 'starson-pos-2025',
    storageBucket: 'starson-pos-2025.firebasestorage.app',
    iosBundleId: 'com.example.starsonFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0CApe1dH9t6Bp-QWM5EIaBHCz6I7FEQ',
    appId: '1:365499300665:web:1b07891b9b9437349146e8',
    messagingSenderId: '365499300665',
    projectId: 'starson-pos-2025',
    authDomain: 'starson-pos-2025.firebaseapp.com',
    storageBucket: 'starson-pos-2025.firebasestorage.app',
  );

}