
from abc import ABC, abstractmethod

class BasePaymentProvider(ABC):
    """
    Abstract base class for all payment providers.
    It defines the standard interface for initiating payments,
    handling callbacks, and checking transaction statuses.
    """

    @abstractmethod
    def get_provider_name(self) -> str:
        """Returns the name of the provider (e.g., 'safaricom_mpesa')."""
        pass

    @abstractmethod
    def initiate_payment(self, txn_id: str, amount: float, phone_number: str, **kwargs) -> dict:
        """
        Initiates a payment request with the provider.

        Args:
            txn_id: The unique transaction ID generated by our system.
            amount: The amount to be paid.
            phone_number: The customer's phone number.
            **kwargs: Additional provider-specific parameters.

        Returns:
            A dictionary containing the provider's response.
        """
        pass

    @abstractmethod
    def handle_callback(self, txn_id: str, data: dict) -> tuple:
        """
        Processes an incoming callback from the payment provider.
        This is used for automatic, server-to-server confirmation.

        Args:
            txn_id: The transaction ID this callback relates to.
            data: The JSON payload from the provider.

        Returns:
            A tuple containing the new status ('completed' or 'failed')
            and a dictionary of relevant data from the callback.
        """
        pass

    def confirm_manual_payment(self, txn_id: str) -> dict:
        """
        Handles manual confirmation by a cashier for payments that
        do not have an automatic callback mechanism.

        Args:
            txn_id: The transaction ID to confirm.

        Returns:
            A dictionary with confirmation details.
        """
        # Default implementation for providers that support this
        import datetime
        confirmation_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return {
            "status": "completed",
            "confirmation_time": confirmation_time,
            "confirmed_manually": True,
            "provider_name": self.get_provider_name()
        }

